version: '3'
services:
  neo4j:
      image: neo4j:3.0
      ports:
       - "7474:7474"
       - "7687:7687"
      ulimits:
        nproc: 40000
        nofile:
            soft: 40000
            hard: 40000